name: Build and Test Package
on: [push, pull_request]
jobs:
  lint:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Tools
        run: |
          python -m pip install --upgrade pip
          python .github/scripts/parse_pyproject_toml.py --section build-system --key requires --array --string > pyproj-requires.txt
          pip install -r requirements_lint.txt -r pyproj-requires.txt
      - name: Static Analysis with pylint
        run: |
          pylint spotfire
      - name: Source Packaging
        run: |
          python setup.py sdist
      - uses: actions/upload-artifact@v2
        with:
          name: sdist
          path: 'dist/**'
      - name: Dynamic Elements
        id: dynamic
        run: |
          echo -n "test-envs=[" >> $GITHUB_OUTPUT
          ls test_requirements_* | sed -e 's/test_requirements_/"/' -e 's/.txt/"/' | tr '\n' ',' | sed -e 's/,$//' >> $GITHUB_OUTPUT
          echo "]" >> $GITHUB_OUTPUT
          echo -n "pythons=" >> $GITHUB_OUTPUT
          cat .github/python-versions.json >> $GITHUB_OUTPUT
    outputs:
      test-environments: ${{ steps.dynamic.outputs.test-envs }}
      python-versions: ${{ steps.dynamic.outputs.pythons }}
  build:
    name: Build Wheels
    needs: lint
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        python-version: ${{ fromJson(needs.lint.outputs.python-versions) }}
        operating-system: ['ubuntu-latest', 'windows-latest']
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Build Requirements
        run: |
          python -m pip install --upgrade pip
          python .github/scripts/parse_pyproject_toml.py --section build-system --key requires --array --string > pyproj-requires.txt
          pip install -r pyproj-requires.txt
      - name: Build Wheel
        run: |
          python setup.py bdist_wheel
      - uses: actions/upload-artifact@v2
        with:
          name: wheel-${{ matrix.python-version }}-${{ matrix.operating-system }}
          path: 'dist/**'
  test:
    name: Test
    needs: [lint, build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJson(needs.lint.outputs.python-versions) }}
        test-environment: ${{ fromJson(needs.lint.outputs.test-environments) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/download-artifact@v2
        with:
          name: wheel-${{ matrix.python-version }}-ubuntu-latest
          path: dist
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dist/*.whl -r test_requirements_${{ matrix.test-environment }}.txt
      - name: Run Tests
        run: |
          python -m spotfire.test
        env:
          RESULTS_NAME: ${{ matrix.python-version }}-${{ matrix.test-environment }}
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-results-${{ matrix.python-version }}-${{ matrix.test-environment }}
          path: 'results-*.xml'

