name: Check Current PyLint
on:
  schedule:
    - cron: '17 17 * * 1'
jobs:
  pylint:
    name: Check PyLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Tools
        run: |
          pip install PyGithub pylint
      - name: Run PyLint
        run: |
          python .github/scripts/run_pylint_check.py --token ${{ secrets.GITHUB_TOKEN }} --repo ${{ github.repository }} --label automated/pylint --src spotfire
